- name: Download Pagespeed Nginx module
  get_url: url=https://github.com/pagespeed/ngx_pagespeed/archive/release-{{ nps_version }}-beta.zip
           dest=/home/ubuntu/release-{{ nps_version }}-beta.zip
  
- name: Unzip Pagespeed Nginx module
  command: unzip -q /home/ubuntu/release-{{ nps_version }}-beta.zip -d /home/ubuntu
  
- name: Download Pagespeed psol
  get_url: url=https://dl.google.com/dl/page-speed/psol/{{ nps_version }}.tar.gz
           dest=/home/ubuntu/ngx_pagespeed-release-{{ nps_version }}-beta/{{ nps_version }}.tar.gz
           
- name: Ungzip Pagespeed psol
  command: tar -xzf /home/ubuntu/ngx_pagespeed-release-{{ nps_version }}-beta/{{ nps_version }}.tar.gz -C /home/ubuntu/ngx_pagespeed-release-{{ nps_version }}-beta/

- name: Download Nginx
  get_url: url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
           dest=/home/ubuntu/nginx-{{ nginx_version }}.tar.gz
           
- name: Ungzip Nginx
  command: tar -xzf /home/ubuntu/nginx-{{ nginx_version }}.tar.gz -C /home/ubuntu
  
- name: Build Nginx with Pagespeed
  sudo: true
  shell: 'cd /home/ubuntu/nginx-{{ nginx_version }};{{ item }}'
  with_items:
    - ./configure --add-module=/home/ubuntu/ngx_pagespeed-release-{{ nps_version }}-beta --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --with-ipv6 --with-http_stub_status_module
    - make
    - make install

- name: Copy nginx configuration file.
  sudo: true
  copy: src={{ ec2_tag_Type }}.conf dest=/etc/nginx/nginx.conf
  
- name: Create Nginx service
  sudo: true
  copy: src=nginx_service dest=/etc/init.d/nginx mode=0755
  
- name: Start nginx and add to boot
  service: name=nginx state=restarted enabled=yes
