- name: Setup autossh
  hosts: tag_Type_{{ type_name }}
  serial: 1
  max_fail_percentage: 49
  sudo: true
  gather_facts: false
  
  tasks:
    - name: Add Compose key to authorized_key
      authorized_key: user=ubuntu
                      key="{{ lookup('file', '/var/lib/awx/.ssh/compose.pub') }}"
                      path=/home/ubuntu/.ssh/authorized_keys
                      state=present
                      manage_dir=no
                      
    - name: Copy startup script
      template: src=conf/autossh.conf dest=/etc/init/autossh.conf owner=root group=root mode=0644
      
    - name: Copy init script
      template: src=conf/autossh_host.conf dest=/etc/init/autossh_host.conf owner=root group=root mode=0644
      
    - name: Copy config file
      template: src=conf/autossh.hosts dest=/etc/autossh.hosts owner=root group=root mode=0644
      
    - name: Start autossh
      service: name=autossh state=started
