---
# This playbook configures and deploys the db server(s)

- hosts: tag_metamorphic
  user: ubuntu
  roles:
  - db
  post_tasks:
    - name: Register instance(s) with ELB
      local_action:
        module: ec2_elb
        region: "{{ ec2_region }}"
        instance_id: "{{ ec2_id }}"
        ec2_elbs: Metamorphic
        enable_availability_zone: false
        state: 'present'
