---
- hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  gather_facts: false
  
  tasks:
    - name: Pull sources from the repository.
      git: repo="{{ type_repo }}"
           dest="{{ type_root }}"
           version="{{ branch }}"
           accept_hostkey=yes
           key_file=/home/ubuntu/.ssh/github
      notify:
        - restart web server
        
    - name: Create the server config directory
      file: group=ubuntu owner=ubuntu mode=755 state=directory path="{{ type_root }}/config"
        
    - name: Upload server configuration.
      copy: src=/var/lib/awx/configs/{{ type_name }}.env dest={{ type_root }}/config/.env group=ubuntu owner=ubuntu
