---
- hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  gather_facts: false
  remote_user: "{{ type_name }}"
  
  tasks:
    - name: Copy /etc/sudoers.d/ssh_auth_sock into place
      sudo: yes
      copy: content='Defaults env_keep += "SSH_AUTH_SOCK"' dest='/etc/sudoers.d/ssh_auth_sock' validate='visudo -cf %s' owner=root group=root mode=0440
    
    - name: Pull sources from the repository.
      git: repo="{{ type_repo }}"
           dest="{{ type_root }}"
           version="{{ branch }}"
           force=yes
           ssh_opts="-o StrictHostKeyChecking=no -o ForwardAgent=yes"
      notify:
        - restart {{ type_name }} server
        
    - name: Upload configuration.
      copy: src="{{ lookup('file', '/var/lib/awx/configs/{{ type_name }}.env') }}" dest={{ type_root }}/config/.env
