---
- hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  gather_facts: false
  
  tasks:
    - name: Pull sources from the repository.
      git: repo="{{ type_repo }}"
           dest="{{ type_root }}"
           version="{{ branch }}"
           force=yes
           ssh_opts="-o StrictHostKeyChecking=no -o ForwardAgent=yes"
      notify:
        - restart {{ type_name }} server
        
    - name: Upload configuration.
      sudo: yes
      copy: src=/var/lib/awx/configs/{{ type_name }}.env dest={{ type_root }}/config/.env
