---
- hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  sudo: true
  sudo_user: "{{ type_name }}"
  gather_facts: false
  
  tasks:
  - name: Add authorized_key
    authorized_key: user=charlie
                    key="{{ lookup('file', '/var/lib/awx/.ssh/.ssh/github.pub') }}"
                    path=/home/{{ type_name }}/.ssh
                    state=present
                    manage_dir=no
  
  - name: Pull sources from the repository.
    git: repo="{{ type_repo }}"
         dest="{{ type_root }}"
         version="{{ branch }}"
         accept_hostkey=yes
         key_file=/home/{{ type_name }}/.ssh/github
    notify:
      - restart {{ type_name }} server
      
  - name: Upload configuration.
    copy: src="{{ lookup('file', '/var/lib/awx/configs/{{ type_name }}.env') }}" dest={{ type_root }}/config/.env
