---
- hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  gather_facts: false
  
  tasks:
    - name: Find Git repo SSH host key
      shell: ssh-keyscan {{ git_repo }}
      register: git_repo_host_key
    
    - name: Add Git repo host key to known_hosts
      lineinfile: create=yes dest=/home/ubuntu/.ssh/known_hosts line='{{ git_repo_host_key.stdout }}' state=present
  
    - name: Pull sources from the repository.
      git: repo="{{ type_repo }}"
           dest="{{ type_root }}"
           version="{{ branch }}"
           ssh_opts="-o ForwardAgent=yes"
      notify:
        - restart {{ type_name }} server
        
    - name: Upload server configuration.
      sudo: yes
      copy: src=/var/lib/awx/configs/{{ type_name }}.env dest={{ type_root }}/config/.env
