---
- hosts: tag_Type_{{ type_name }}
  serial: 1
  max_fail_percentage: 49
  gather_facts: false
  
  tasks:
    - name: Pull sources from the repository.
      git: repo="{{ type_repo }}"
           dest="{{ type_root }}"
           version="{{ branch }}"
           accept_hostkey=yes
           key_file=/home/ubuntu/.ssh/github
        
    - name: NPM install
      npm: path="{{ type_root }}"
        
    - name: Create the server config directory
      file: group=ubuntu owner=ubuntu mode=755 state=directory path="{{ type_root }}/config"
        
    - name: Upload server configuration.
      copy: src=/var/lib/awx/configs/{{ type_name }}.env dest={{ type_root }}/config/.env group=ubuntu owner=ubuntu
      
    - name: Restart application server
      sudo: yes
      supervisorctl: name={{ type_name }} state=restarted
      
    - name: Delete Nginx cache
      sudo: yes
      file: path=/var/cache/nginx state=absent
      
    - name: Recreate Nginx cache
      sudo: yes
      file: group=www-data owner=www-data mode=755 state=directory path=/var/cache/nginx
