---
- hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  gather_facts: false
  sudo: true
  sudo_user: "{{ type_user }}"
  
  tasks:
    - name: Pull sources from the repository.
      git: repo="{{ type_repo }}"
           dest="{{ type_root }}"
           version="{{ branch }}"
           accept_hostkey=yes
           key_file=/home/{{ type_name }}/.ssh/github
           force=yes
      notify:
        - restart {{ type_name }} server
        
    - name: Upload configuration.
      copy: src="{{ lookup('file', '/var/lib/awx/configs/{{ type_name }}.env') }}" dest={{ type_root }}/config/.env
