---
# This playbook deploys the whole web application stack in this site.

# Configure and deploy the db server(s)
- hosts: tag_metamorphic
  user: ubuntu
  roles:
  - db
  post_tasks:
    - name: Register instance(s) with ELB
      local_action:
        module: ec2_elb
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: Metamorphic
        state: 'present'

# Configure and deploy the API server(s)
- hosts: tag_type_igneous
  user: ubuntu
  roles:
  - common
  - nginx
  - nodejs
  - api
  post_tasks:
    - name: Register instance(s) with ELB
      local_action:
        module: ec2_elb
        region: "{{ ec2_region }}"
        instance_id: "{{ ec2_id }}"
        ec2_elbs: Igneous-VPC
        state: 'present'
        wait_timeout: 60

# Configure and deploy the web server(s)
- hosts: tag_type_sedimentary
  user: ubuntu
  roles:
  - common
  - nginx
  - nodejs
  - web
  post_tasks:
    - name: Register instance(s) with ELB
      local_action:
        module: ec2_elb
        region: "{{ ec2_region }}"
        instance_id: "{{ ec2_id }}"
        ec2_elbs: Sedimentary-VPC
        state: 'present'
        wait_timeout: 60
