---
- name: Sedimentary Provisioning
  hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  sudo: true
  gather_facts: false
  tasks:
    - name: Create the server directory.
      file: state=directory path="{{ type_root }}"
      
    - name: Create user.
      user: home=/home/{{ type_name }} name="{{ type_name }}" state=present
      
    - name: Update the server directory
      file: group="{{ type_name }}" owner="{{ type_name }}" mode=755 state=directory path="{{ type_root }}"
      
    - name: Install system packages
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: system_packages
      
    - name: Create alternatives link for Node
      alternatives: link=/usr/bin/node name=nodejs path=/usr/bin/nodejs
      
    - name: Create the SSH directory.
      file: state=directory path=/home/{{ type_name }}/.ssh
      
    - name: Set up SSH key
      authorized_key: user="{{ type_name }}"
                      key="{{ lookup('file', '/var/lib/awx/.ssh/github.pub') }}"
                      path=/home/{{ type_name }}/.ssh
                      manage_dir=no
    
    - name: Copy nginx configuration file.
      copy: src=conf/nginx.conf dest=/etc/nginx/nginx.conf
      notify: restart nginx
      
    - name: Copy web server startup script
      template: src=conf/{{ type_name }}_startup.conf.j2 dest=/etc/init/{{ type_name }}.conf backup=yes mode=0644
    
  handlers:
    - include: handlers.yml
      
- include: deploy.yml
