---
- name: Sedimentary Provisioning
  hosts: tag_Type_sedimentary
  serial: 1
  max_fail_percentage: 49
  sudo: true
  gather_facts: false
  tasks:
    - name: Create user.
      user: home=/home/{{ type_name }} name="{{ type_name }}" state=present
      
    - name: Create the server directory
      file: group="{{ type_name }}" owner="{{ type_name }}" mode=755 state=directory path="{{ type_root }}"
      
    - name: Install system packages
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: system_packages
      
    - name: Create alternatives link for Node
      alternatives: link=/usr/bin/node name=nodejs path=/usr/bin/nodejs
      
    - name: Create the SSH directory.
      file: state=directory path=/home/{{ type_name }}/.ssh group="{{ type_name }}" owner="{{ type_name }}"
                      
    - name: Copy SSH key
      copy: src=/var/lib/awx/.ssh/github dest=/home/{{ type_name }}/.ssh/github mode=0600 group="{{ type_name }}" owner="{{ type_name }}"
      
    - name: Make sure the known_hosts file exists
      file: path=/home/{{ type_name }}/.ssh/known_hosts state=touch group="{{ type_name }}" owner="{{ type_name }}"
                      
    - name: Download Pagespeed Nginx module
      get_url: url=https://github.com/pagespeed/ngx_pagespeed/archive/release-{{ nps_version }}-beta.zip
               dest=/home/{{ type_name }}/release-{{ nps_version }}-beta.zip
      
    - name: Unzip Pagespeed Nginx module
      command: unzip -q /home/{{ type_name }}/release-{{ nps_version }}-beta.zip -d /home/{{ type_name }}
      
    - name: Download Pagespeed psol
      get_url: url=https://dl.google.com/dl/page-speed/psol/{{ nps_version }}.tar.gz
               dest=/home/{{ type_name }}/ngx_pagespeed-release-{{ nps_version }}-beta/{{ nps_version }}.tar.gz
               
    - name: Ungzip Pagespeed psol
      command: tar -xzf /home/{{ type_name }}/ngx_pagespeed-release-{{ nps_version }}-beta/{{ nps_version }}.tar.gz -C /home/{{ type_name }}/ngx_pagespeed-release-{{ nps_version }}-beta/
    
    - name: Download Nginx
      get_url: url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
               dest=/home/{{ type_name }}/nginx-{{ nginx_version }}.tar.gz
               
    - name: Ungzip Nginx
      command: tar -xzf /home/{{ type_name }}/nginx-{{ nginx_version }}.tar.gz -C /home/{{ type_name }}
      
    - name: Build Nginx with Pagespeed
      shell: 'cd /home/{{ type_name }}/nginx-{{ nginx_version }};{{ item }}'
      with_items:
        - ./configure --add-module=/home/{{ type_name }}/ngx_pagespeed-release-{{ nps_version }}-beta --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --with-ipv6 --with-http_stub_status_module
        - make
        - make install
    
    - name: Copy nginx configuration file.
      copy: src=conf/nginx.conf dest=/etc/nginx/nginx.conf
      
    - name: Create Nginx service
      copy: src=conf/nginx_service dest=/etc/init.d/nginx mode=0755
      
    - name: Start nginx
      service: name=nginx state=started
      
    - name: Copy web server startup script
      template: src=conf/{{ type_name }}_startup.conf.j2 dest=/etc/init/{{ type_name }}.conf mode=0644
    
  handlers:
    - include: handlers.yml
      
- include: deploy.yml
