---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: tag_test_true
  user: root
  roles:
  - common

# Configure and deploy the API/DB server(s)
- hosts: tag_test_true
  user: root
  roles:
  - nginx
  - api

# Configure and deploy the web server(s)
- hosts: tag_Type_sedimentary2
  user: root
  roles:
  - nginx
  - web
