---
# This playbook deploys the whole application stack in this site.

# Configure and deploy the API server(s)
- hosts: tag_type_igneous
  user: ubuntu
  roles:
  - common
  - nginx
  - nodejs
  - api

# Configure and deploy the web server(s)
- hosts: tag_type_sedimentary
  user: ubuntu
  roles:
  - common
  - nginx
  - nodejs
  - web
