---
# This playbook configures and deploys the web server(s).

- hosts: tag_type_sedimentary
  user: ubuntu
  roles:
  - common
  - nginx
  - nodejs
  - web
  post_tasks:
    - name: Register instance(s) with ELB
      local_action:
        module: ec2_elb
        region: "{{ ec2_region }}"
        instance_id: "{{ ec2_id }}"
        ec2_elbs: Sedimentary-VPC
        state: 'present'
        wait_timeout: 60
