---
- name: Install git
  sudo: true
  apt: pkg=git state=installed update-cache=yes

- name: Pull sources from the repository.
  git: repo=ssh://git@github.com/3digitalrock/igneous.git
       dest=/var/www/igneous
       version="{{ branch }}"
       accept_hostkey=yes
       key_file=/home/ubuntu/.ssh/github
       force=yes
    
- name: NPM install
  npm: path=/var/www/igneous
    
- name: Create the server config directory
  file: group=ubuntu owner=ubuntu mode=755 state=directory path=/var/www/igneous/config
    
- name: Upload server configuration
  copy: src=/var/lib/awx/configs/igneous.env dest=/var/www/igneous/config/.env group=ubuntu owner=ubuntu
  
- name: Install Forever
  npm: name=forever global=yes state=latest
  
- name: Check list of Node.js apps running
  command: forever list
  register: forever_list
  changed_when: false

- name: Make sure igneous is started
  command: forever start /path/to/app.js
  when: "forever_list.stdout.find('/var/www/igneous/server.js') == -1"
  
- name: Delete Nginx cache
  sudo: true
  file: path=/var/cache/nginx state=absent
  
- name: Recreate Nginx cache
  sudo: true
  file: group=www-data owner=www-data mode=755 state=directory path=/var/cache/nginx
