- name: Create the server directory
  sudo: true
  file: group=ubuntu owner=ubuntu mode=755 state=directory path=/var/www/{{ ec2_tag_Type }}
  
- name: Install nodejs packages
  sudo: true
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: nodejs_packages
  
- name: Create alternatives link for Node
  sudo: true
  alternatives: link=/usr/bin/node name=nodejs path=/usr/bin/nodejs

- name: Install supervisord
  sudo: true
  easy_install: name=supervisor
