- name: Create the server directory
  sudo: true
  file: group=ubuntu owner=ubuntu mode=755 state=directory path=/var/www/{{ ec2_tag_type }}
  
- name: Install nodejs packages
  sudo: true
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: nodejs_packages

- name: Create symlink to 'node'
  sudo: true
  file: src=/usr/bin/nodejs dest=/usr/bin/node owner=root group=root state=link
