- name: Create the server directory
  file: group=ubuntu owner=ubuntu mode=755 state=directory path="{{ type_root }}"
  
- name: Install nodejs packages
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: nodejs_packages
  
- name: Create alternatives link for Node
  alternatives: link=/usr/bin/node name=nodejs path=/usr/bin/nodejs
