- name: Install supervisord
  sudo: true
  easy_install: name=supervisor

- name: Copy supervisord init script
  sudo: true
  copy: src=supervisord dest=/etc/init.d/supervisord owner=root group=root mode=755
  
- name: Create the supervisord log directory.
  sudo: true
  file: state=directory path=/var/log/supervisor group=root owner=root
