- name: Add RethinkDB repo
  sudo: true
  shell: . /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | tee /etc/apt/sources.list.d/rethinkdb.list
  
- name: Get and add repo key
  sudo: true
  apt_key: url=http://download.rethinkdb.com/apt/pubkey.gpg
  
- name: Install RethinkDB
  sudo: true
  apt: pkg=rethinkdb state=installed update-cache=yes
  
- name: Copy configuration file
  sudo: true
  template: src=instance1.conf.j2 dest=/etc/rethinkdb/instances.d/instance1.conf
  notify:
  - restart rethinkdb

- name: Download ruxit agent
  get_url: url=https://yiuhjezdah.live.ruxit.com/installer/agent/unix/latest/dt1Ii5a7TPNWE3R9
           dest=/home/ubuntu/ruxit-agent.sh
           force=yes
           
- name: Set permissions on ruxit agent
  file: path=/home/ubuntu/ruxit-agent.sh mode=0744 state=file
           
- name: Install ruxit agent
  sudo: true
  shell: ruxit-agent.sh chdir=/home/ubuntu/
