    - name: Set timezone to Eastern
      command: timedatectl set-timezone America/New_York
  
    - name: Verify ubuntu user exists
      user: home=/home/ubuntu name=ubuntu state=present
      
    - name: Create the SSH directory.
      file: state=directory path=/home/ubuntu/.ssh group=ubuntu owner=ubuntu
                      
    - name: Copy Github Deploy SSH key
      copy: src=/var/lib/awx/.ssh/github.{{ ec2_tag_Type }} dest=/home/ubuntu/.ssh/github mode=0600 group=ubuntu owner=ubuntu

    - name: Copy SSH config file
      copy: src=/var/lib/awx/.ssh/config dest=/home/ubuntu/.ssh/config group=ubuntu owner=ubuntu
      
    - name: Make sure the known_hosts file exists
      file: path=/home/ubuntu/.ssh/known_hosts state=touch group=ubuntu owner=ubuntu
      
    - name: Make sure the authorized_key file exists
      file: path=/home/ubuntu/.ssh/authorized_keys state=touch group=ubuntu owner=ubuntu
  
    - name: Add SSH keys to authorized_key
      authorized_key: user=ubuntu key=https://github.com/synth3tk.keys
      
    - name: Install system packages
      sudo: true
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: system_packages
